primary_agent:
  llm: gpt-4o-mini
  llm_temperature: 0.0

document_rag_pdf:
  unstructured_docs: src/backend/media/data/docs/doc_pdf
  llm: gpt-4o-mini
  collection_name: rag-mongo
  db_name: docpdf
  embedding_model: text-embedding-3-small
  k: 2
  llm_temperature: 0.0
  chunk_size: 500
  chunk_overlap: 100


sqlagent_configs:
  sqldb_dir: ""
  llm: "gpt-3.5-turbo"
  llm_temperature: 0.0



langsmith:
  tracing: "true"
  project_name: "rag_sqlagent_project"

tavily_search_api:
  tavily_search_max_results: 2

graph_configs:
  thread_id: 1 #